import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/molecules/navBar";
import NavBarMobile from "@/components/molecules/navBarMobile";
import MyFooter from "@/components/atoms/footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{scrollBehavior: "smooth"}}
      >
        <div className="hidden md:block"><NavBar /></div>
        <div className="md:hidden"><NavBarMobile /></div>
        {children}
        <MyFooter />
      </body>
    </html>
  );
}
